name = "American Standard Version (1901) Footnotes"
description = 'Footnotes based on the "American Standard Version (1901)" Bible'
bible = "American Standard Version (1901)"
license = "https://ebible.org/Scriptures/details.php?id=eng-asv"
language = "eng"
data_source = "https://ebible.org/Scriptures/details.php?id=eng-asv"
